Server:
  WebPort: 80
  NetCatPort: 9999
  Address: 127.0.0.1
  SSl: False

Paths:
  DataStorage: ./storage
  HtmlStorage: ./lib/html

DataStorage:
  FilesExpires: true
  ExpireTime: 14d
  CleanerExecutionTime: 5m